/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cw.http;

import java.io.IOException;
import java.io.InputStream;
import java.net.ServerSocket;
import java.net.Socket;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException {
        ServerSocket server = new ServerSocket(10000);
        while(true){
            System.out.println("Wait for connection...");
            Socket connection = server.accept();
            System.out.println("Connected");

            // connection.getInputStream();
            // connection.getOutputStream();

            InputStream is = connection.getInputStream();

            String requestText = readAll(is);
            HttpRequest request = HttpRequest.of(requestText);

            System.out.println("################# START #################");
            System.out.println(requestText);
            System.out.println("****************** END ******************");
            System.out.println("-----------------------------------------");
            System.out.println("################# START #################");
            System.out.println(request);
            System.out.println("****************** END ******************");
        }
    }

    private static String readAll(InputStream is) throws InterruptedException, IOException {
        Thread.sleep(1000L);
        byte[] buffer = new byte[1024 * 20];
        int length = 0;
        while(is.available() > 0){
            int read = is.read(buffer, length, is.available());
            length += read;
            Thread.sleep(1000L);
        }
        return new String(buffer, 0, length);
    }
}
