/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cw.http;

import java.io.IOException;
import java.io.InputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.Objects;

public class App {
    public static void main(String[] args){
        // localhost:10000
        try(ServerSocket server = new ServerSocket(10000)){
            while(true){
                System.out.println("Wait for connection...");
                Socket connection = server.accept();
                System.out.println("Connected");
                try(InputStream is = connection.getInputStream()){
                    final String requestText = readAll(is);
                    if(!Objects.equals(requestText.strip(), "")){
                        HttpRequest request = HttpRequest.of(requestText);
                        // System.out.println(requestText);
                        // System.out.println(request);
                        HttpResponse response = new HttpResponse();
                        response.setStatusCode(200);
                        response.setStatusText("Ok");
                        response.setBody("<h1>Hello!</h1>");
                        String respText = response.toString();
                        byte[] responseBytes = respText.getBytes(StandardCharsets.UTF_8);
                        connection.getOutputStream().write(responseBytes);
                    }
                } catch (IOException | InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static String readAll(InputStream is) throws InterruptedException, IOException {
        Thread.sleep(1000L);
        byte[] buffer = new byte[1024 * 20];
        int length = 0;
        while(is.available() > 0){
            int read = is.read(buffer, length, is.available());
            length += read;
            Thread.sleep(1000L);
        }
        return new String(buffer, 0, length);
    }
}
